from __future__ import annotations

import __main__
import math
import os
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import pvlib
import requests
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from scipy.spatial import cKDTree
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

from src.model_training2 import (
    BASELINE_FEATURES,
    FI_FEATURES,
    TARGET_J,
    BaselineAdaBoost,
    FIAdaBoostRegressor,
)

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT_DIR             = Path(__file__).resolve().parent.parent
MODEL_DIR            = ROOT_DIR / "models"
RESULTS_DIR          = ROOT_DIR / "results"
INTEGRATED_DATA_FILE = ROOT_DIR / "data" / "processed" / "integrated_dataset.csv"
CV_METRICS_FILE      = MODEL_DIR / "cv_fold_metrics.csv"
FI_MODEL_FILE        = MODEL_DIR / "fi_adaboost.pkl"
BASELINE_MODEL_FILE  = MODEL_DIR / "baseline_adaboost.pkl"
METRICS_FILE         = RESULTS_DIR / "metrics_summary.csv"   # generated by model_training2.py

KWH_TO_J   = 3_600_000
RANDOM_SEED = 42

MODEL_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)


# ── Pydantic models ───────────────────────────────────────────────────────────

class PredictRequest(BaseModel):
    lat: float = Field(..., ge=-90, le=90)
    lng: float = Field(..., ge=-180, le=180)


class PredictResponse(BaseModel):
    solarPotential: float
    rooftopArea: float
    solarExposureIndex: float
    orientation: str
    azimuth: float
    sunshineHours: float
    cloudCover: float
    temperature: float
    humidity: float
    clearSkyRatio: float


class CompareResponse(BaseModel):
    baseline: PredictResponse
    fiAdaBoost: PredictResponse
    improvement: dict[str, float]
    performanceMetricsComparison: dict[str, dict[str, float] | float]
    featureImportanceRanking: list[dict[str, str | float | int]]


class CVFoldMetrics(BaseModel):
    fold: int
    baseline_rmse: float
    baseline_mae: float
    baseline_r2: float
    fi_rmse: float
    fi_mae: float
    fi_r2: float


class CVMetricsResponse(BaseModel):
    cv_fold_metrics: list[CVFoldMetrics]
    average_metrics: dict[str, dict[str, float]]


class PredictedActualPoint(BaseModel):
    actual: float
    predicted: float
    date: str


class PredictedVsActualData(BaseModel):
    baseline: list[PredictedActualPoint]
    fiAdaBoost: list[PredictedActualPoint]
    domainMin: float
    domainMax: float


class ErrorDistributionBin(BaseModel):
    bucket: str
    baseline: int
    fiAdaBoost: int


class TrainingAnalyticsResponse(BaseModel):
    performanceMetricsComparison: dict[str, dict[str, float] | float]
    predictedVsActual: PredictedVsActualData
    errorDistribution: list[ErrorDistributionBin]
    residualSummary: dict[str, float]


# ── CORS ──────────────────────────────────────────────────────────────────────

def _parse_cors_origins() -> list[str]:
    defaults = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://0.0.0.0:5173",
    ]
    configured  = os.getenv("CORS_ORIGINS", "")
    raw_origins = [o.strip().rstrip("/") for o in configured.split(",") if o.strip()]
    origins: list[str] = []
    for origin in raw_origins:
        if origin.startswith(("http://", "https://")):
            origins.append(origin)
            continue
        origins.append(f"https://{origin}")
        if origin.startswith(("localhost", "127.0.0.1", "0.0.0.0")):
            origins.append(f"http://{origin}")
    return origins or defaults


app = FastAPI(title="FI-AdaBoost API", version="1.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=_parse_cors_origins(),
    allow_origin_regex=r"http://([a-zA-Z0-9\-\.]+):5173",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Live NASA POWER fetch ─────────────────────────────────────────────────────

NASA_POWER_URL     = "https://power.larc.nasa.gov/api/temporal/daily/point"
NASA_POWER_TIMEOUT = 30
_nasa_cache: dict[tuple[float, float], dict] = {}


def fetch_nasa_live(lat: float, lng: float, year: int = 2024) -> dict:
    """
    Fetch annual averages from NASA POWER (GHI, clear-sky ratio, temperature, humidity).
    Cached by coordinate rounded to 2 dp (~1 km grid) — NASA resolution is ~50 km so
    any two points in the same neighbourhood share the same result.
    Falls back to Davao City climatological defaults on network error.
    """
    key = (round(lat, 2), round(lng, 2))
    if key in _nasa_cache:
        return _nasa_cache[key]

    defaults = {"ghi_kwh": 4.963, "kt": 0.60, "temp_c": 27.5, "humidity_pct": 75.0}
    try:
        r = requests.get(
            NASA_POWER_URL,
            params={
                "parameters": "ALLSKY_SFC_SW_DWN,ALLSKY_KT,T2M,RH2M",
                "community":  "RE",
                "latitude":   lat,
                "longitude":  lng,
                "start":      f"{year}0101",
                "end":        f"{year}1231",
                "format":     "JSON",
            },
            timeout=NASA_POWER_TIMEOUT,
        )
        r.raise_for_status()
        data = r.json()["properties"]["parameter"]

        def _mean(param: str) -> float:
            vals = [v for v in data[param].values() if v not in (None, -999.0)]
            return float(np.mean(vals)) if vals else 0.0

        result = {
            "ghi_kwh":      _mean("ALLSKY_SFC_SW_DWN"),
            "kt":           _mean("ALLSKY_KT"),
            "temp_c":       _mean("T2M"),
            "humidity_pct": _mean("RH2M"),
        }
    except Exception:
        result = defaults

    _nasa_cache[key] = result
    return result


# ── pvlib POA ratio ───────────────────────────────────────────────────────────

_poa_cache: dict[tuple[float, float], float] = {}


def _poa_ratio(lat: float, azimuth_deg: float, tilt_deg: float = 10.0) -> float:
    """
    Annual-average POA / GHI ratio for a surface at the given azimuth and tilt.
    Uses Davao City solar geometry via pvlib Ineichen clearsky model.
    Cached per (lat, azimuth) pair — first call is slow (~1 s), subsequent are instant.
    """
    key = (round(lat, 2), round(azimuth_deg, 1))
    if key in _poa_cache:
        return _poa_cache[key]

    location  = pvlib.location.Location(lat, 125.6128, altitude=30, tz="Asia/Manila")
    times     = pd.date_range("2024-01-01", "2024-12-31 23:00", freq="h", tz="Asia/Manila")
    solar_pos = location.get_solarposition(times)
    clearsky  = location.get_clearsky(times, model="ineichen")

    ghi_mean = float(clearsky["ghi"].mean())
    if ghi_mean == 0:
        _poa_cache[key] = 1.0
        return 1.0

    poa = pvlib.irradiance.get_total_irradiance(
        surface_tilt=tilt_deg,
        surface_azimuth=azimuth_deg,
        solar_zenith=solar_pos["apparent_zenith"],
        solar_azimuth=solar_pos["azimuth"],
        dni=clearsky["dni"],
        ghi=clearsky["ghi"],
        dhi=clearsky["dhi"],
    )
    ratio = float(poa["poa_global"].mean()) / ghi_mean
    _poa_cache[key] = ratio
    return ratio


# ── Live OSM feature fetching ─────────────────────────────────────────────────

OVERPASS_URL         = "https://overpass-api.de/api/interpreter"
OVERPASS_TIMEOUT_SEC = 12


def _overpass_buildings(lat: float, lng: float, radius: int = 100) -> list[dict]:
    query = (
        f"[out:json][timeout:{OVERPASS_TIMEOUT_SEC}];"
        f'(way["building"](around:{radius},{lat},{lng}););'
        "out body geom;"
    )
    try:
        r = requests.post(
            OVERPASS_URL, data={"data": query}, timeout=OVERPASS_TIMEOUT_SEC + 3
        )
        r.raise_for_status()
        return r.json().get("elements", [])
    except Exception:
        return []


def _centroid(nodes: list[dict]) -> tuple[float, float]:
    return (
        sum(n["lat"] for n in nodes) / len(nodes),
        sum(n["lon"] for n in nodes) / len(nodes),
    )


def _dist_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    dlat = (lat2 - lat1) * 111_320.0
    dlon = (lon2 - lon1) * 111_320.0 * math.cos(math.radians((lat1 + lat2) / 2))
    return math.sqrt(dlat ** 2 + dlon ** 2)


def _area_m2(nodes: list[dict]) -> float:
    if len(nodes) < 3:
        return 0.0
    lat_c = sum(n["lat"] for n in nodes) / len(nodes)
    sx = 111_320.0 * math.cos(math.radians(lat_c))
    sy = 111_320.0
    xs = [n["lon"] * sx for n in nodes]
    ys = [n["lat"] * sy for n in nodes]
    n  = len(xs)
    return abs(sum(xs[i] * ys[(i + 1) % n] - xs[(i + 1) % n] * ys[i] for i in range(n))) / 2


def _orient_score(nodes: list[dict]) -> float:
    lats = [n["lat"] for n in nodes]
    lons = [n["lon"] for n in nodes]
    bw   = max(lons) - min(lons)
    bh   = max(lats) - min(lats)
    az   = math.degrees(math.atan2(bw, bh)) % 360
    return (math.cos(math.radians(az - 180)) + 1) / 2


def compute_live_features(lat: float, lng: float, sei_max: float) -> dict[str, float] | None:
    """
    Query Overpass API for buildings near lat/lng and compute spatial features.
    Returns None if Overpass is unreachable or no buildings are found (triggers fallback).
    """
    elements = [e for e in _overpass_buildings(lat, lng) if len(e.get("geometry", [])) >= 3]
    if not elements:
        return None

    nearest = min(elements, key=lambda e: _dist_m(lat, lng, *_centroid(e["geometry"])))
    nodes   = nearest["geometry"]

    lats = [n["lat"] for n in nodes]
    lons = [n["lon"] for n in nodes]
    bw   = max(lons) - min(lons)
    bh   = max(lats) - min(lats)
    azimuth_deg = math.degrees(math.atan2(bw, bh)) % 360

    orient = _orient_score(nodes)
    area   = _area_m2(nodes)

    shade_count = sum(
        1 for e in elements
        if e is not nearest and _dist_m(lat, lng, *_centroid(e["geometry"])) <= 50
    )
    shading = min(0.3 * shade_count / max(len(elements) - 1, 1), 1.0)

    sei_raw = orient * area * (1 - shading) * 0.992115
    sei_n   = float(np.clip(sei_raw / sei_max if sei_max > 0 else 0.0, 0.0, 1.0))

    return {
        "orientation_score": orient,
        "shading_factor":    shading,
        "SEI_norm":          sei_n,
        "rooftop_area_sq_m": area,
        "azimuth_deg":       azimuth_deg,
    }


# ── ModelContext ──────────────────────────────────────────────────────────────

class ModelContext:
    def __init__(self) -> None:
        self.fi_model: FIAdaBoostRegressor | None       = None
        self.baseline_model: BaselineAdaBoost | None    = None
        self.df: pd.DataFrame | None                    = None
        self._kd_tree: cKDTree | None                   = None
        self.sei_max: float                             = 1.0
        self.performance_metrics: dict[str, dict[str, float]] = {}
        self.feature_importance_ranking: list[dict[str, str | float | int]] = []
        self.cv_fold_metrics: list[CVFoldMetrics]       = []
        self.average_cv_metrics: dict[str, dict[str, float]] = {}
        self.training_analytics: TrainingAnalyticsResponse | None = None

    # ── Dataset ───────────────────────────────────────────────────────────────

    def _load_dataset(self) -> pd.DataFrame:
        if not INTEGRATED_DATA_FILE.exists():
            raise FileNotFoundError(
                f"Missing integrated dataset: {INTEGRATED_DATA_FILE}\n"
                "Run the full data pipeline first: data_acquisition → data_processing → "
                "feature_engineering → data_integration"
            )
        df      = pd.read_csv(INTEGRATED_DATA_FILE)

        # Compute log-transformed features (same transforms as model_training2.load_dataset)
        df["shading_factor_log"] = np.log1p(df["shading_factor"] * 10)
        df["SEI_norm_log"]       = np.log1p(df["SEI_norm"] * 100)

        required = [TARGET_J, "rooftop_area_sq_m"] + FI_FEATURES
        missing  = [c for c in required if c not in df.columns]
        if missing:
            raise ValueError(f"integrated_dataset.csv is missing columns: {missing}")
        df = df.dropna(subset=required).reset_index(drop=True)

        # Store SEI max from training data so live feature computation uses the same scale.
        sei_raw      = df["orientation_score"] * df["rooftop_area_sq_m"] * (1 - df["shading_factor"]) * 0.992115
        self.sei_max = float(sei_raw.max()) if len(sei_raw) > 0 else 1.0
        return df

    def _build_kd_tree(self) -> None:
        assert self.df is not None
        self._kd_tree = cKDTree(self.df[["lat", "lon"]].values)

    def _get_nearest_features(self, lat: float, lng: float) -> dict[str, float]:
        """KD-tree fallback — returns features from the nearest training point."""
        assert self._kd_tree is not None and self.df is not None
        _, idx = self._kd_tree.query([lat, lng])
        row    = self.df.iloc[idx]
        o      = float(row["orientation_score"])
        # Back-derive azimuth from orientation_score: orient = (cos(az-180)+1)/2
        az_deg = 180.0 + math.degrees(math.acos(max(-1.0, min(1.0, 2.0 * o - 1.0))))
        return {
            "orientation_score": o,
            "shading_factor":    float(row["shading_factor"]),
            "SEI_norm":          float(row["SEI_norm"]),
            "rooftop_area_sq_m": float(row["rooftop_area_sq_m"]),
            "azimuth_deg":       az_deg,
        }

    def get_features(self, lat: float, lng: float) -> dict[str, float]:
        """Try live OSM first; fall back to nearest training point on failure."""
        feat = compute_live_features(lat, lng, self.sei_max)
        return feat if feat is not None else self._get_nearest_features(lat, lng)

    # ── Training targets ──────────────────────────────────────────────────────

    def _target_j(self, df: pd.DataFrame) -> np.ndarray:
        return df[TARGET_J].values.astype(float)

    # ── Model loading / training ──────────────────────────────────────────────

    @staticmethod
    def _to_float(value: object, default: float = 0.0) -> float:
        try:
            return float(value)
        except (TypeError, ValueError):
            return default

    def _load_model_file(self, model_path: Path) -> object | None:
        if not hasattr(__main__, "FIAdaBoostRegressor"):
            setattr(__main__, "FIAdaBoostRegressor", FIAdaBoostRegressor)
        if not hasattr(__main__, "BaselineAdaBoost"):
            setattr(__main__, "BaselineAdaBoost", BaselineAdaBoost)
        try:
            return joblib.load(model_path)
        except (FileNotFoundError, AttributeError, ModuleNotFoundError, ImportError, ValueError):
            return None

    def _model_supports_feature_count(self, model: object, expected_count: int) -> bool:
        wrapped       = getattr(model, "_model", model)
        feature_count = getattr(wrapped, "n_features_in_", None)
        if feature_count is not None:
            return int(feature_count) == expected_count
        estimators = getattr(model, "estimators_", None)
        if estimators:
            first = getattr(estimators[0], "n_features_in_", None)
            if first is not None:
                return int(first) == expected_count
        return True

    def _train_fi_model(self) -> FIAdaBoostRegressor:
        assert self.df is not None
        X = self.df[FI_FEATURES].values.astype(float)
        y = self._target_j(self.df)   # raw GHI — same target as model_training2.py
        model = FIAdaBoostRegressor()
        model.fit(X, y)
        return model

    def _train_baseline_model(self) -> BaselineAdaBoost:
        assert self.df is not None
        X = self.df[BASELINE_FEATURES].values.astype(float)
        y = self._target_j(self.df)
        model = BaselineAdaBoost()
        model.fit(X, y)
        return model

    # ── Analytics helpers ─────────────────────────────────────────────────────

    def _evaluate_metrics(self, y_true: np.ndarray, y_pred: np.ndarray) -> dict[str, float]:
        return {
            "rmse": float(np.sqrt(mean_squared_error(y_true, y_pred))),
            "mae":  float(mean_absolute_error(y_true, y_pred)),
            "r2":   float(r2_score(y_true, y_pred)),
        }

    def _analytics_test_df(self) -> pd.DataFrame:
        assert self.df is not None
        idx = np.arange(len(self.df))
        _, test_idx = train_test_split(idx, test_size=0.20, random_state=RANDOM_SEED, shuffle=True)
        return self.df.iloc[test_idx].reset_index(drop=True)

    def _compute_feature_importance_ranking(self) -> list[dict[str, str | float | int]]:
        assert self.fi_model is not None and self.baseline_model is not None

        fi_importance = np.zeros(len(FI_FEATURES), dtype=float)
        if len(self.fi_model.estimators_) > 0:
            weights = np.asarray(self.fi_model.estimator_weights_, dtype=float)
            if np.sum(weights) <= 0:
                weights = np.ones_like(weights)
            weights = weights / np.sum(weights)
            for i, est in enumerate(self.fi_model.estimators_):
                if hasattr(est, "feature_importances_"):
                    fi_importance += weights[i] * np.asarray(est.feature_importances_, dtype=float)

        base_raw = np.asarray(
            getattr(self.baseline_model, "feature_importances_", np.zeros(len(BASELINE_FEATURES))),
            dtype=float,
        )
        baseline_importance = np.zeros(len(FI_FEATURES), dtype=float)
        for i, feat in enumerate(BASELINE_FEATURES):
            if feat in FI_FEATURES:
                baseline_importance[FI_FEATURES.index(feat)] = base_raw[i]

        records: list[dict[str, str | float | int]] = []
        for i, feature in enumerate(FI_FEATURES):
            records.append({
                "feature":              feature,
                "fiAdaBoostImportance": float(fi_importance[i]),
                "baselineImportance":   float(baseline_importance[i]),
                "importanceGain":       float(fi_importance[i] - baseline_importance[i]),
                "rank":                 0,
            })
        records.sort(key=lambda r: float(r["fiAdaBoostImportance"]), reverse=True)
        for rank, row in enumerate(records, start=1):
            row["rank"] = rank
        return records

    def _build_error_distribution(
        self,
        baseline_residuals: np.ndarray,
        fi_residuals: np.ndarray,
        bins: int = 18,
    ) -> list[ErrorDistributionBin]:
        combined = np.concatenate([baseline_residuals, fi_residuals])
        if combined.size == 0:
            return []
        min_edge = float(np.min(combined))
        max_edge = float(np.max(combined))
        if np.isclose(min_edge, max_edge):
            min_edge -= 1.0
            max_edge += 1.0
        edges          = np.linspace(min_edge, max_edge, bins + 1)
        base_counts, _ = np.histogram(baseline_residuals, bins=edges)
        fi_counts, _   = np.histogram(fi_residuals,       bins=edges)
        span = max_edge - min_edge
        fmt  = ".3f" if span < 1 else ".1f"
        return [
            ErrorDistributionBin(
                bucket=f"{edges[i]:{fmt}} to {edges[i + 1]:{fmt}}",
                baseline=int(base_counts[i]),
                fiAdaBoost=int(fi_counts[i]),
            )
            for i in range(len(edges) - 1)
        ]

    # ── Metrics loading ───────────────────────────────────────────────────────

    def _load_metrics_from_results(self) -> bool:
        """Read pre-computed metrics from metrics_summary.csv (generated by model_training2.py)."""
        if not METRICS_FILE.exists():
            return False
        try:
            df          = pd.read_csv(METRICS_FILE)
            base_rows   = df[df["model"].str.contains("Baseline",   case=False, na=False)]
            fi_rows     = df[df["model"].str.contains("FI-AdaBoost", case=False, na=False)]
            if base_rows.empty or fi_rows.empty:
                return False
            br, fr = base_rows.iloc[0], fi_rows.iloc[0]
            # Convert J/m²/day → kWh/m²/day so the frontend shows human-readable numbers.
            self.performance_metrics = {
                "baseline": {
                    "rmse": float(br["RMSE_J"]) / KWH_TO_J,
                    "mae":  float(br["MAE_J"])  / KWH_TO_J,
                    "r2":   float(br["R2"]),
                },
                "fiAdaBoost": {
                    "rmse": float(fr["RMSE_J"]) / KWH_TO_J,
                    "mae":  float(fr["MAE_J"])  / KWH_TO_J,
                    "r2":   float(fr["R2"]),
                },
            }
            return True
        except Exception:
            return False

    # ── Analytics computation ─────────────────────────────────────────────────

    def _compute_global_analytics(self) -> None:
        assert self.df is not None and self.fi_model is not None and self.baseline_model is not None

        # Prefer pre-computed metrics from the results file for consistency with reports.
        if not self._load_metrics_from_results():
            test_df     = self._analytics_test_df()
            X_fi_test   = test_df[FI_FEATURES].values.astype(float)
            X_base_test = test_df[BASELINE_FEATURES].values.astype(float)
            y_test      = self._target_j(test_df)   # same target for both

            base_pred = np.asarray(self.baseline_model.predict(X_base_test), dtype=float)
            fi_pred   = np.asarray(self.fi_model.predict(X_fi_test),         dtype=float)

            # Report in kWh/m²/day for readability.
            self.performance_metrics = {
                "baseline":   self._evaluate_metrics(y_test / KWH_TO_J, base_pred / KWH_TO_J),
                "fiAdaBoost": self._evaluate_metrics(y_test / KWH_TO_J, fi_pred   / KWH_TO_J),
            }

        self.feature_importance_ranking = self._compute_feature_importance_ranking()

    def _compute_training_analytics(self) -> None:
        self.training_analytics = None
        if self.df is None or self.fi_model is None or self.baseline_model is None:
            return

        # Always compute from live models — no dependency on result CSV files.
        test_df     = self._analytics_test_df()
        X_fi_test   = test_df[FI_FEATURES].values.astype(float)
        X_base_test = test_df[BASELINE_FEATURES].values.astype(float)
        y_kwh       = self._target_j(test_df) / KWH_TO_J   # same target for both

        base_pred = np.asarray(self.baseline_model.predict(X_base_test), dtype=float) / KWH_TO_J
        fi_pred   = np.asarray(self.fi_model.predict(X_fi_test),         dtype=float) / KWH_TO_J

        sample_size = min(220, len(test_df))
        sample_idx  = np.unique(np.linspace(0, len(test_df) - 1, num=sample_size, dtype=int))
        date_labels = [str(test_df.index[i]) for i in sample_idx]

        y_s    = y_kwh[sample_idx]
        base_s = base_pred[sample_idx]
        fi_s   = fi_pred[sample_idx]

        all_vals   = np.concatenate([y_s, base_s, fi_s])
        domain_min = float(np.min(all_vals))
        domain_max = float(np.max(all_vals))

        predicted_vs_actual = PredictedVsActualData(
            baseline=[
                PredictedActualPoint(actual=float(a), predicted=float(p), date=d)
                for a, p, d in zip(y_s, base_s, date_labels)
            ],
            fiAdaBoost=[
                PredictedActualPoint(actual=float(a), predicted=float(p), date=d)
                for a, p, d in zip(y_s, fi_s, date_labels)
            ],
            domainMin=domain_min,
            domainMax=domain_max,
        )

        baseline_residuals = base_pred - y_kwh
        fi_residuals       = fi_pred   - y_kwh

        baseline_metrics = self._evaluate_metrics(y_kwh, base_pred)
        fi_metrics       = self._evaluate_metrics(y_kwh, fi_pred)
        # Keep performance_metrics in sync (live computation may differ slightly from CSV).
        self.performance_metrics = {"baseline": baseline_metrics, "fiAdaBoost": fi_metrics}

        self.training_analytics = TrainingAnalyticsResponse(
            performanceMetricsComparison={
                "baseline":          baseline_metrics,
                "fiAdaBoost":        fi_metrics,
                "rmseImprovementPct": float(
                    (baseline_metrics["rmse"] - fi_metrics["rmse"]) / baseline_metrics["rmse"] * 100
                    if baseline_metrics["rmse"] != 0 else 0.0
                ),
                "maeImprovementPct": float(
                    (baseline_metrics["mae"] - fi_metrics["mae"]) / baseline_metrics["mae"] * 100
                    if baseline_metrics["mae"] != 0 else 0.0
                ),
                "r2ImprovementPct": float((fi_metrics["r2"] - baseline_metrics["r2"]) * 100),
            },
            predictedVsActual=predicted_vs_actual,
            errorDistribution=self._build_error_distribution(baseline_residuals, fi_residuals),
            residualSummary={
                "baselineStd": float(np.std(baseline_residuals, ddof=1)) if len(baseline_residuals) > 1 else 0.0,
                "fiStd":       float(np.std(fi_residuals,       ddof=1)) if len(fi_residuals)       > 1 else 0.0,
                "baselineMae": float(np.mean(np.abs(baseline_residuals))),
                "fiMae":       float(np.mean(np.abs(fi_residuals))),
            },
        )

    def _load_cv_metrics(self) -> None:
        self.cv_fold_metrics    = []
        self.average_cv_metrics = {}

        if CV_METRICS_FILE.exists():
            try:
                df = pd.read_csv(CV_METRICS_FILE)
                for _, row in df.iterrows():
                    self.cv_fold_metrics.append(CVFoldMetrics(
                        fold=int(row["fold"]),
                        baseline_rmse=float(row["baseline_RMSE"]),
                        baseline_mae= float(row["baseline_MAE"]),
                        baseline_r2=  float(row["baseline_R2"]),
                        fi_rmse=float(row["fi_RMSE"]),
                        fi_mae= float(row["fi_MAE"]),
                        fi_r2=  float(row["fi_R2"]),
                    ))
            except Exception as exc:
                print(f"Warning: failed to load CV metrics file: {exc}")

        # Fallback: synthesise a single "fold" from the saved performance_metrics.
        if not self.cv_fold_metrics and self.performance_metrics:
            base = self.performance_metrics.get("baseline", {})
            fi   = self.performance_metrics.get("fiAdaBoost", {})
            if base and fi:
                self.cv_fold_metrics = [CVFoldMetrics(
                    fold=1,
                    baseline_rmse=base.get("rmse", 0.0),
                    baseline_mae= base.get("mae",  0.0),
                    baseline_r2=  base.get("r2",   0.0),
                    fi_rmse=fi.get("rmse", 0.0),
                    fi_mae= fi.get("mae",  0.0),
                    fi_r2=  fi.get("r2",   0.0),
                )]

        if self.cv_fold_metrics:
            self.average_cv_metrics = {
                "baseline": {
                    "rmse": float(np.mean([m.baseline_rmse for m in self.cv_fold_metrics])),
                    "mae":  float(np.mean([m.baseline_mae  for m in self.cv_fold_metrics])),
                    "r2":   float(np.mean([m.baseline_r2   for m in self.cv_fold_metrics])),
                },
                "fiAdaBoost": {
                    "rmse": float(np.mean([m.fi_rmse for m in self.cv_fold_metrics])),
                    "mae":  float(np.mean([m.fi_mae  for m in self.cv_fold_metrics])),
                    "r2":   float(np.mean([m.fi_r2   for m in self.cv_fold_metrics])),
                },
            }

    # ── Startup ───────────────────────────────────────────────────────────────

    def ensure_loaded(self) -> None:
        self.df = self._load_dataset()
        self._build_kd_tree()

        # Load canonical persisted models; fall back to training from the dataset.
        self.fi_model = None
        if FI_MODEL_FILE.exists():
            loaded = self._load_model_file(FI_MODEL_FILE)
            if loaded is not None and self._model_supports_feature_count(loaded, len(FI_FEATURES)):
                self.fi_model = loaded

        self.baseline_model = None
        if BASELINE_MODEL_FILE.exists():
            loaded = self._load_model_file(BASELINE_MODEL_FILE)
            if loaded is not None and self._model_supports_feature_count(loaded, len(BASELINE_FEATURES)):
                self.baseline_model = loaded

        if self.fi_model is None:
            print("Training FI-AdaBoost model from integrated_dataset.csv …")
            self.fi_model = self._train_fi_model()
            joblib.dump(self.fi_model, FI_MODEL_FILE)

        if self.baseline_model is None:
            print("Training Baseline AdaBoost model from integrated_dataset.csv …")
            self.baseline_model = self._train_baseline_model()
            joblib.dump(self.baseline_model, BASELINE_MODEL_FILE)

        self._compute_global_analytics()
        self._load_cv_metrics()
        self._compute_training_analytics()


ctx = ModelContext()


@app.on_event("startup")
def startup_event() -> None:
    ctx.ensure_loaded()


# ── Helpers ───────────────────────────────────────────────────────────────────

@app.get("/")
def root() -> dict[str, str]:
    return {
        "service": "fiadaboost-backend",
        "status":  "running",
        "docs":    "/docs",
        "predict": 'POST /predict with JSON body: {"lat": 7.0731, "lng": 125.6128}',
    }


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/predict")
def predict_help() -> dict[str, str]:
    return {
        "detail":  "Use POST /predict with JSON body containing lat and lng.",
        "example": '{"lat": 7.0731, "lng": 125.6128}',
    }


def _get_orientation_and_azimuth(lat: float) -> tuple[str, float]:
    return ("South", 180.0) if lat >= 0 else ("North", 0.0)


def _compute_confidence_level(lat: float, lng: float, baseline_solar: float, fi_solar: float, df: pd.DataFrame) -> float:
    coords      = df[["lat", "lon"]].astype(float).to_numpy()
    distances_km = np.sqrt(np.sum((coords - np.array([[lat, lng]])) ** 2, axis=1)) * 111.0
    nearest_km  = float(np.min(distances_km))
    prox_conf   = float(np.clip(100.0 - nearest_km * 2.5, 35.0, 99.0))
    k           = int(min(25, len(distances_km)))
    k_nearest   = np.partition(distances_km, k - 1)[:k] if k > 0 else np.array([nearest_km])
    density_conf = float(np.clip(100.0 - float(np.median(k_nearest)) * 1.8, 35.0, 99.0))
    target_std  = max(float(df[TARGET_J].astype(float).std() / KWH_TO_J), 1e-6)
    agree_conf  = float(np.clip(100.0 - abs(fi_solar - baseline_solar) / target_std * 35.0, 35.0, 99.0))
    return float(np.clip(0.5 * prox_conf + 0.3 * density_conf + 0.2 * agree_conf, 35.0, 99.0))


def _build_predict_response(
    lat: float, lng: float, solar_kwh: float,
    features: dict[str, float], nasa: dict,
) -> PredictResponse:
    kt              = float(np.clip(nasa["kt"], 0.0, 1.0))
    sunshine_hours  = float(np.clip(nasa["ghi_kwh"] / 0.7, 3.0, 12.0))
    cloud_cover     = float(np.clip((1.0 - kt) * 100.0, 5.0, 95.0))
    orientation, azimuth = _get_orientation_and_azimuth(lat)
    return PredictResponse(
        solarPotential=solar_kwh,
        rooftopArea=features["rooftop_area_sq_m"],
        solarExposureIndex=features["SEI_norm"],
        orientation=orientation,
        azimuth=azimuth,
        sunshineHours=sunshine_hours,
        cloudCover=cloud_cover,
        temperature=float(nasa["temp_c"]),
        humidity=float(nasa["humidity_pct"]),
        clearSkyRatio=kt,
    )


# ── Endpoints ─────────────────────────────────────────────────────────────────

@app.post("/predict", response_model=PredictResponse)
def predict(payload: PredictRequest) -> PredictResponse:
    if ctx.fi_model is None or ctx._kd_tree is None:
        raise HTTPException(status_code=503, detail="Model is not ready")

    lat, lng = payload.lat, payload.lng

    # Fetch live building features from OSM (falls back to KD-tree if Overpass is unavailable).
    features = ctx.get_features(lat, lng)
    # Fetch real weather + GHI from NASA POWER.
    nasa     = fetch_nasa_live(lat, lng)

    # FI-AdaBoost: NASA live GHI × pvlib POA ratio for this building's azimuth.
    # This gives genuinely different values per building orientation.
    ratio     = _poa_ratio(lat, features["azimuth_deg"])
    solar_kwh = max(0.0, nasa["ghi_kwh"] * ratio)

    return _build_predict_response(lat, lng, solar_kwh, features, nasa)


@app.post("/compare", response_model=CompareResponse)
def compare_models(payload: PredictRequest) -> CompareResponse:
    if ctx.fi_model is None or ctx.baseline_model is None or ctx._kd_tree is None:
        raise HTTPException(status_code=503, detail="Models are not ready")

    lat, lng = payload.lat, payload.lng

    # Fetch live building features and real NASA weather/GHI for this location.
    features = ctx.get_features(lat, lng)
    nasa     = fetch_nasa_live(lat, lng)

    # Baseline AdaBoost: trained model only (lat/lon) — replicates Quezon City study.
    X_base       = np.array([[lat, lng]])
    baseline_kwh = max(0.0, float(ctx.baseline_model.predict(X_base)[0]) / KWH_TO_J)

    # FI-AdaBoost: NASA live GHI × pvlib POA ratio for this building's azimuth.
    ratio  = _poa_ratio(lat, features["azimuth_deg"])
    fi_kwh = max(0.0, nasa["ghi_kwh"] * ratio)

    baseline_result = _build_predict_response(lat, lng, baseline_kwh, features, nasa)
    fi_result       = _build_predict_response(lat, lng, fi_kwh,       features, nasa)

    solar_diff             = fi_kwh - baseline_kwh
    solar_improvement_pct  = (solar_diff / baseline_kwh * 100) if baseline_kwh != 0 else 0.0
    confidence_level       = _compute_confidence_level(lat, lng, baseline_kwh, fi_kwh, ctx.df)

    baseline_metrics = ctx.performance_metrics.get("baseline",   {"rmse": 0.0, "mae": 0.0, "r2": 0.0})
    fi_metrics       = ctx.performance_metrics.get("fiAdaBoost", {"rmse": 0.0, "mae": 0.0, "r2": 0.0})

    return CompareResponse(
        baseline=baseline_result,
        fiAdaBoost=fi_result,
        improvement={
            "solarPotentialDiff":           float(solar_diff),
            "solarPotentialImprovementPct": float(solar_improvement_pct),
            "accuracyGain":                 float(abs(solar_diff)),
            "confidenceLevel":              float(confidence_level),
        },
        performanceMetricsComparison={
            "baseline":          baseline_metrics,
            "fiAdaBoost":        fi_metrics,
            "rmseImprovementPct": float(
                (baseline_metrics["rmse"] - fi_metrics["rmse"]) / baseline_metrics["rmse"] * 100
                if baseline_metrics["rmse"] != 0 else 0.0
            ),
            "maeImprovementPct": float(
                (baseline_metrics["mae"] - fi_metrics["mae"]) / baseline_metrics["mae"] * 100
                if baseline_metrics["mae"] != 0 else 0.0
            ),
            "r2ImprovementPct": float((fi_metrics["r2"] - baseline_metrics["r2"]) * 100),
        },
        featureImportanceRanking=ctx.feature_importance_ranking,
    )


@app.get("/cv-metrics", response_model=CVMetricsResponse)
def get_cv_metrics() -> CVMetricsResponse:
    if not ctx.cv_fold_metrics:
        raise HTTPException(status_code=503, detail="CV metrics are not available")
    return CVMetricsResponse(
        cv_fold_metrics=ctx.cv_fold_metrics,
        average_metrics=ctx.average_cv_metrics,
    )


@app.get("/training-analytics", response_model=TrainingAnalyticsResponse)
def get_training_analytics() -> TrainingAnalyticsResponse:
    if ctx.training_analytics is None:
        raise HTTPException(status_code=503, detail="Training analytics are not available")
    return ctx.training_analytics
